import Head from "../node_modules/next/head";
import { useRouter } from "../node_modules/next/router";
import type { NextPage } from "next";
import { Box } from "@academy/ui";

const Home: NextPage = () => {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Academy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
        <Box bg="background.main" height="100%">
          hi
        </Box>
      </body>
    </>
  );
};

export default Home;
